### ISSUE TITLE
Convert Static data to YAML

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-ui#458]

**Comment by putmantime** [comment]
@vincerubinetti I am beginning work on this issue.  Is it appropriate to move the data to a yaml directory in assets?
e.g. /assetts/yaml
I don't see any aggregation of static files currently

**Comment by vincerubinetti** [comment]
Yeah you can create a folder as you feel appropriate. You might just name it `/static` or something, to have it less tethered to the particular format (maybe we convert it to json at some point? idk).

I might make it a top level folder too, so we have `/src/assets` for things like images and `/src/static` for things like yaml and markdown.

**Comment by putmantime** [comment]
Sounds good.  I'll just start by creating the static files in /src/static and not update the code to use them yet.

**Comment by vincerubinetti** [comment]
Here's an example of a way to construct a yaml file out of this data in a way that's helpful for display purposes:

```yaml
- group: University of Colorado Anschutz Medical Campus:
  members:
  - name: Melissa Haendel
    role: PI
    image: images/melissa-haendel.jpg
    description: text text text
  - name: another person
    # ...
  - name: another person
    # ...
  - name: another person
    # ...

- group: Oregon State University:
  members:
    - name: Tom Conlin
     # ...
```

The exact structure and name of keys can be changed later, but this is a general example. Also remember that order of keys can't be guaranteed, so use actual lists when you need order (e.g. Melissa first, CU first).
